[About]
  Title = ""
  Description = ""
  Show = false

  [[About.Items]]
    PersonName = ""
    PersonPosition = ""
    Description = ""
    Image = ""
    Alt = ""
    Show = false

[GalleryStore]
  Title = ""
  Description = ""
  Show = false

  [[GalleryStore.Galleries]]
    ID = ""
    Name = ""
    Description = ""
    GallerySource = ""
    Show = false

    [[GalleryStore.Galleries.Images]]
      Source = ""
      Alt = ""
      Caption = ""
      Width = 0
      Height = 0
